  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - idea-holiday-tour-maker-1-0
      - --image
      - gcr.io/$PROJECT_ID/ideaholidaytourmaker1.0:$COMMIT_SHA
      - --region
      - us-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "80"
